[bumpver]
current_version = "23.1"
version_pattern = "YY.PATCH"
commit_message = "bump version -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"mailkuk/version.go" = [
    'const VERSION = "{version}"',
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
